export const DEMO_DATA = {
  '3-6': {
    label: 'Micul explorator (3–6 ani)',
    emoji: '🧸',
    tasks1: [
      { id: 't1_1', name: 'Mi-am periat dintii', pts: 2 },
      { id: 't1_2', name: 'M-am spalat pe maini', pts: 2 },
      { id: 't1_3', name: 'Mi-am strans jucariile', pts: 3 },
      { id: 't1_4', name: 'Am mancat tot din farfurie', pts: 3 },
      { id: 't1_5', name: 'M-am imbracat singur', pts: 2 },
      { id: 't1_6', name: 'Am adormit la ora stabilita', pts: 3 },
    ],
    bonus1: 5,
    tasks2: [
      { id: 't2_1', name: 'Am impartit jucaria cu altcineva', pts: 3 },
      { id: 't2_2', name: 'Am spus va rog si multumesc', pts: 2 },
      { id: 't2_3', name: 'Am ascultat din prima', pts: 4 },
      { id: 't2_4', name: 'Am ajutat fara sa fiu rugat', pts: 3 },
    ],
    bonus2: 6,
    penalties: [
      { id: 'p1', name: 'A facut tantrum', pts: 3 },
      { id: 'p2', name: 'A muscat / lovit', pts: 5 },
      { id: 'p3', name: 'Nu a ascultat dupa 3 avertismente', pts: 3 },
    ],
    rewards: [
      { id: 'r1', icon: '📺', name: '+15 min desene animate', pts: 10, type: 'timp', dailyLimit: 2, weeklyLimit: null },
      { id: 'r2', icon: '📖', name: 'O poveste in plus la culcare', pts: 8, type: 'special', dailyLimit: 1, weeklyLimit: null },
      { id: 'r3', icon: '🍬', name: 'O dulciurica', pts: 6, type: 'special', dailyLimit: 1, weeklyLimit: null },
      { id: 'r4', icon: '🛝', name: 'Iesire la locul de joaca', pts: 20, type: 'special', dailyLimit: null, weeklyLimit: 3 },
      { id: 'r5', icon: '🎮', name: 'Joc cu mama/tata (30 min)', pts: 15, type: 'timp', dailyLimit: 1, weeklyLimit: null },
    ],
    starValue: 0.10,
    maxLv1: 500, maxLv2: 800, maxLv3: 1200,
  },
  '7-10': {
    label: 'Aventurierul (7–10 ani)',
    emoji: '🚀',
    tasks1: [
      { id: 't1_1', name: 'Tema facuta complet', pts: 5 },
      { id: 't1_2', name: 'Camera strans si organizata', pts: 4 },
      { id: 't1_3', name: 'Dinti spalati dimineata si seara', pts: 3 },
      { id: 't1_4', name: 'Am citit 15 minute', pts: 4 },
      { id: 't1_5', name: 'Am adormit la ora stabilita', pts: 3 },
      { id: 't1_6', name: 'Rucsacul pregatit pentru scoala', pts: 2 },
    ],
    bonus1: 8,
    tasks2: [
      { id: 't2_1', name: 'Am ajutat la spalat vasele', pts: 4 },
      { id: 't2_2', name: 'Am hranit animalul de companie', pts: 3 },
      { id: 't2_3', name: 'Am fost politicos cu vizitatorii', pts: 3 },
      { id: 't2_4', name: 'Nu m-am certat cu fratele/sora', pts: 5 },
      { id: 't2_5', name: 'Am facut sport / miscare', pts: 4 },
    ],
    bonus2: 10,
    penalties: [
      { id: 'p1', name: 'Minciuna dovedita', pts: 8 },
      { id: 'p2', name: 'Tema neinceputa fara motiv', pts: 6 },
      { id: 'p3', name: 'Cearta / plans exagerat', pts: 4 },
      { id: 'p4', name: 'A stricat intentionat ceva', pts: 10 },
    ],
    rewards: [
      { id: 'r1', icon: '📱', name: '+30 min tableta / jocuri', pts: 15, type: 'timp', dailyLimit: 2, weeklyLimit: null },
      { id: 'r2', icon: '🎬', name: 'Alegerea filmului de vineri', pts: 20, type: 'special', dailyLimit: null, weeklyLimit: 1 },
      { id: 'r3', icon: '🍔', name: 'O iesire la McDonalds', pts: 60, type: 'special', dailyLimit: null, weeklyLimit: 1 },
      { id: 'r4', icon: '💰', name: '10 RON in pusculita', pts: 80, type: 'bani', dailyLimit: null, weeklyLimit: null },
      { id: 'r5', icon: '👫', name: 'Invitatia unui prieten la joaca', pts: 50, type: 'special', dailyLimit: null, weeklyLimit: 1 },
      { id: 'r6', icon: '🎮', name: 'Joc nou (ales impreuna)', pts: 150, type: 'special', dailyLimit: null, weeklyLimit: null },
    ],
    starValue: 0.10,
    maxLv1: 800, maxLv2: 1200, maxLv3: 2000,
  },
  '11-14': {
    label: 'Campionul (11–14 ani)',
    emoji: '🎯',
    tasks1: [
      { id: 't1_1', name: 'Toate temele predate la timp', pts: 6 },
      { id: 't1_2', name: 'Camera curata si patul facut', pts: 4 },
      { id: 't1_3', name: 'Am studiat extra 30 min', pts: 5 },
      { id: 't1_4', name: 'Nu am folosit telefonul dupa ora 21', pts: 5 },
      { id: 't1_5', name: 'Am facut sport', pts: 4 },
      { id: 't1_6', name: 'Am citit o carte (15 min)', pts: 3 },
    ],
    bonus1: 20,
    tasks2: [
      { id: 't2_1', name: 'Am aspirat / maturit', pts: 5 },
      { id: 't2_2', name: 'Am facut cumparaturi singur', pts: 6 },
      { id: 't2_3', name: 'Am gatit ceva simplu', pts: 8 },
      { id: 't2_4', name: 'Am ingrijit fratele / sora mai mic', pts: 7 },
      { id: 't2_5', name: 'Am spalat / uscat rufele', pts: 5 },
    ],
    bonus2: 15,
    penalties: [
      { id: 'p1', name: 'Nota mica din nepasare', pts: 15 },
      { id: 'p2', name: 'Minciuna / ascuns ceva', pts: 20 },
      { id: 'p3', name: 'Telefon dupa ora interzisa', pts: 10 },
      { id: 'p4', name: 'Atitudine nepotrivita', pts: 8 },
    ],
    rewards: [
      { id: 'r1', icon: '📱', name: '+1h timp liber ecran', pts: 20, type: 'timp', dailyLimit: 2, weeklyLimit: null },
      { id: 'r2', icon: '🎉', name: 'Iesire cu prietenii (aprobata)', pts: 80, type: 'special', dailyLimit: null, weeklyLimit: 2 },
      { id: 'r3', icon: '💰', name: '25 RON pentru ce vrea', pts: 200, type: 'bani', dailyLimit: null, weeklyLimit: null },
      { id: 'r4', icon: '🎬', name: 'Acces Netflix / gaming 1 seara', pts: 30, type: 'timp', dailyLimit: null, weeklyLimit: 3 },
      { id: 'r5', icon: '🎵', name: 'Concert / eveniment ales', pts: 300, type: 'special', dailyLimit: null, weeklyLimit: null },
      { id: 'r6', icon: '🎁', name: 'Obiect dorit (pana la 100 RON)', pts: 500, type: 'bani', dailyLimit: null, weeklyLimit: null },
    ],
    starValue: 0.10,
    maxLv1: 1000, maxLv2: 1800, maxLv3: 3000,
  },
  '14-18': {
    label: 'Liderul (14–18 ani)',
    emoji: '🏆',
    tasks1: [
      { id: 't1_1', name: 'Medie saptamanala peste 8', pts: 15 },
      { id: 't1_2', name: 'Activitate fizica 3x/saptamana', pts: 10 },
      { id: 't1_3', name: 'Fara retele sociale inainte de teme', pts: 8 },
      { id: 't1_4', name: 'Am invatat ceva nou (curs, carte)', pts: 10 },
      { id: 't1_5', name: 'Am ajutat un coleg cu o problema', pts: 6 },
    ],
    bonus1: 30,
    tasks2: [
      { id: 't2_1', name: 'Am facut curatenie generala', pts: 10 },
      { id: 't2_2', name: 'Am gatit masa pentru familie', pts: 12 },
      { id: 't2_3', name: 'Am gestionat un buget (cumparaturi)', pts: 10 },
      { id: 't2_4', name: 'Am ingrijit un membru al familiei', pts: 10 },
      { id: 't2_5', name: 'Am reparat / montat ceva singur', pts: 8 },
    ],
    bonus2: 25,
    penalties: [
      { id: 'p1', name: 'Absent nemotivat de la scoala', pts: 30 },
      { id: 'p2', name: 'Minciuna grava / incredere incalcata', pts: 50 },
      { id: 'p3', name: 'Depasit ora de acasa', pts: 20 },
      { id: 'p4', name: 'Comportament neadecvat la scoala', pts: 25 },
    ],
    rewards: [
      { id: 'r1', icon: '💵', name: '50 RON bani de buzunar', pts: 400, type: 'bani', dailyLimit: null, weeklyLimit: null },
      { id: 'r2', icon: '🌙', name: 'Iesire weekend fara curfew strict', pts: 150, type: 'special', dailyLimit: null, weeklyLimit: 1 },
      { id: 'r3', icon: '🎵', name: 'Abonament lunar (Spotify etc.)', pts: 200, type: 'bani', dailyLimit: null, weeklyLimit: null },
      { id: 'r4', icon: '🎁', name: 'Obiect dorit (pana la 200 RON)', pts: 800, type: 'bani', dailyLimit: null, weeklyLimit: null },
      { id: 'r5', icon: '✈️', name: 'Vacanta / excursie cu prietenii', pts: 1500, type: 'special', dailyLimit: null, weeklyLimit: null },
      { id: 'r6', icon: '🚗', name: 'Permis auto (contributie parinti)', pts: 3000, type: 'special', dailyLimit: null, weeklyLimit: null },
    ],
    starValue: 0.10,
    maxLv1: 2000, maxLv2: 3500, maxLv3: 6000,
  },
}
